INSERT INTO regiones (id,nombre) VALUES(1,'Sudameria');
INSERT INTO regiones (id,nombre) VALUES(2,'Centroameria');
INSERT INTO regiones (id,nombre) VALUES(3,'Norteameria');
INSERT INTO regiones (id,nombre) VALUES(4,'Europa');
INSERT INTO regiones (id,nombre) VALUES(5,'Asia');
INSERT INTO regiones (id,nombre) VALUES(6,'Africa');
INSERT INTO regiones (id,nombre) VALUES(7,'Oceania');
INSERT INTO regiones (id,nombre) VALUES(8,'Antartida');

INSERT INTO clientes (region_id,nombre,apellido,email,create_at) VALUES(1,'Jade','Due','betito1@hotmail.com','2023-02-22');
INSERT INTO clientes (region_id,nombre,apellido,email,create_at) VALUES(4,'Juan','Apellido2','betito2@hotmail.com','2023-02-22');
INSERT INTO clientes (region_id,nombre,apellido,email,create_at) VALUES(5,'Toño','Apellido3','betito3@hotmail.com','2023-02-22');
INSERT INTO clientes (region_id,nombre,apellido,email,create_at) VALUES(6,'Pedro','Apellido4','betito4@hotmail.com','2023-02-22');
INSERT INTO clientes (region_id,nombre,apellido,email,create_at) VALUES(6,'Paco','Apellido5','betito5@hotmail.com','2023-02-22');
INSERT INTO clientes (region_id,nombre,apellido,email,create_at) VALUES(8,'Pablo','Apellido6','betito6@hotmail.com','2023-02-22');
INSERT INTO clientes (region_id,nombre,apellido,email,create_at) VALUES(2,'Tito','Apellido7','betito7@hotmail.com','2023-02-22');
INSERT INTO clientes (region_id,nombre,apellido,email,create_at) VALUES(3,'Jose','Apellido8','betito8@hotmail.com','2023-02-22');
INSERT INTO clientes (region_id,nombre,apellido,email,create_at) VALUES(4,'Julio','Apellido9','betito9@hotmail.com','2023-02-22');
INSERT INTO clientes (region_id,nombre,apellido,email,create_at) VALUES(6,'Jonas','Apellido10','betito10@hotmail.com','2023-02-22');